// Runtime-agnostic contract flow. Runs unchanged on Node, Bun and in a browser bundle, so it
// uses no host API beyond the language itself: no node:assert, no process, no Bun globals.
// It receives the module namespace of the *packed* application-exception artifact.

export class FlowAssertionError extends Error {}

const fail = (message) => {
  throw new FlowAssertionError(message);
};
const ok = (value, message) => {
  if (!value) fail(message);
};
const equal = (actual, expected, message) => {
  if (actual !== expected)
    fail(
      `${message}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`,
    );
};
const deepEqual = (actual, expected, message) => {
  const a = JSON.stringify(actual);
  const b = JSON.stringify(expected);
  if (a !== b) fail(`${message}: expected ${b}, got ${a}`);
};

/**
 * Defines a typed exception, builds both reports, decodes the public one, and checks that the
 * occurrence ids correlate and the schema versions match the constants the package exports.
 * Returns a plain JSON-safe summary so a driver can print or transport it.
 */
export function runFlow(appex, { runtime }) {
  for (const name of [
    'defineException',
    'toDiagnosticReport',
    'toPublicReport',
    'toReports',
    'decodePublicReport',
    'createRedactionPolicy',
    'createTrustRealm',
    'isTypedException',
    'restoreExpectedValues',
    'DIAGNOSTIC_REPORT_VERSION',
    'PUBLIC_REPORT_VERSION',
    'APPEX_ERROR_CODES',
  ]) {
    ok(appex[name] !== undefined, `packed artifact must export ${name}`);
  }

  const {
    defineException,
    toDiagnosticReport,
    toPublicReport,
    decodePublicReport,
    isTypedException,
    DIAGNOSTIC_REPORT_VERSION,
    PUBLIC_REPORT_VERSION,
  } = appex;

  const ToolFailure = defineException({
    tag: 'agent/ToolFailure',
    message: ({ tool }) => `${tool} failed`,
    public: { code: 'TOOL_FAILED', details: ({ tool }) => ({ tool }) },
  });

  const cause = new Error('connection refused');
  const error = new ToolFailure({ details: { tool: 'search' }, cause });

  ok(error instanceof Error, 'a typed exception is an Error');
  ok(
    error instanceof ToolFailure,
    'a typed exception is an instance of its constructor',
  );
  ok(isTypedException(error), 'isTypedException recognises the exception');
  equal(error._tag, 'agent/ToolFailure', '_tag');
  equal(error.name, 'agent/ToolFailure', 'name');
  equal(error.message, 'search failed', 'message');
  equal(error.cause, cause, 'cause');

  // Occurrence ids are generated by nanoid. In a browser this must go through
  // nanoid's browser build (crypto.getRandomValues), never node:crypto.
  const occurrenceId = error.occurrenceId;
  equal(typeof occurrenceId, 'string', 'occurrenceId type');
  ok(
    /^AE_[0-9ABCDEFGHJKMNPQRSTVWXYZ]{26}$/.test(occurrenceId),
    `occurrenceId must be a prefixed 26-character crockford id, got ${occurrenceId}`,
  );
  const second = new ToolFailure({ details: { tool: 'search' } }).occurrenceId;
  ok(second !== occurrenceId, 'occurrence ids must be unique per exception');

  const diagnostic = toDiagnosticReport(error, { context: { runtime } });
  const publicReport = toPublicReport(error);

  equal(diagnostic.v, DIAGNOSTIC_REPORT_VERSION, 'diagnostic schema version');
  equal(diagnostic.v, 'corj/v0.12', 'diagnostic schema version literal');
  equal(publicReport.v, PUBLIC_REPORT_VERSION, 'public schema version');
  equal(publicReport.v, 'appex/public/v3', 'public schema version literal');

  equal(
    diagnostic.occurrence_id,
    occurrenceId,
    'diagnostic occurrence_id correlates',
  );
  equal(
    publicReport.occurrence_id,
    occurrenceId,
    'public occurrence_id correlates',
  );

  deepEqual(
    publicReport,
    {
      v: 'appex/public/v3',
      occurrence_id: occurrenceId,
      code: 'TOOL_FAILED',
      message: 'Something went wrong',
      as_json: { tool: 'search' },
    },
    'public report shape',
  );
  ok(
    !JSON.stringify(publicReport).includes('connection refused'),
    'the public report must not leak the cause',
  );
  equal(
    diagnostic.children &&
      diagnostic.children[0] &&
      diagnostic.children[0].path,
    '$.cause',
    'the diagnostic report carries the cause',
  );
  equal(
    appex.restoreExpectedValues(diagnostic).message,
    'search failed',
    'restoreExpectedValues',
  );

  // Cross the transport boundary the way a caller would.
  const decoded = decodePublicReport(JSON.parse(JSON.stringify(publicReport)));
  ok(
    decoded.ok,
    `decodePublicReport must accept a round-tripped report: ${decoded.reason}`,
  );
  equal(
    decoded.report.occurrence_id,
    occurrenceId,
    'decoded occurrence_id correlates',
  );
  equal(decoded.report.code, 'TOOL_FAILED', 'decoded code');

  const rejected = decodePublicReport({ v: 'appex/public/v3' });
  ok(!rejected.ok, 'decodePublicReport must reject a malformed report');

  equal(
    toPublicReport(new Error('x')).code,
    'INTERNAL_ERROR',
    'untyped fallback code',
  );

  let invalidCodeError;
  try {
    toPublicReport(error, { code: '' });
  } catch (thrown) {
    invalidCodeError = thrown;
  }
  ok(
    invalidCodeError instanceof TypeError &&
      invalidCodeError.code === 'APPEX_INVALID_PUBLIC_CODE',
    'an invalid public code raises APPEX_INVALID_PUBLIC_CODE',
  );

  return {
    runtime,
    occurrenceId,
    diagnosticVersion: diagnostic.v,
    publicVersion: publicReport.v,
    diagnosticOccurrenceId: diagnostic.occurrence_id,
    publicOccurrenceId: publicReport.occurrence_id,
    decodedOccurrenceId: decoded.report.occurrence_id,
    code: decoded.report.code,
  };
}
