name: Run Tests and npm publish
on:
  push:
    branches:
      - main
jobs:
  node_18_compatibility:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 18
          cache: npm

      - name: Install
        run: npm ci

      - name: Run tests
        run: npm run test-ci

  test_and_release:
    needs: node_18_compatibility
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install
        run: npm ci

      #      - name: Compare npm with local (versions)
      #        uses: Rober19/compare-npm-versions-ci@master
      #        id: package_version
      #        with:
      #          path: './'
      #          npm_package_name: pojo-constructor
      #
      #      - name: Get version
      #        run: |
      #          echo "Version is  ${{ steps.package_version.outputs.version }} "
      #          echo "Version NPM is  ${{ steps.package_version.outputs.pkg_npm_version }} "
      #          echo "Is greater ${{steps.package_version.outputs.npm_is_greater}}'

      - name: Run tests
        run: npm run test-ci

      - name: Generating coverage badges
        uses: 'jpb06/jest-badges-action@latest'
        with:
          branches: main
          coverage-summary-path: ./coverage/coverage-summary.json
          commit-message: 'chore: Update tests coverage badges [skip ci]'
          commit-user: github-actions[bot]
          commit-user-email: github-actions[bot]@users.noreply.github.com

      - name: Build
        run: npm run prepublish-me

      - uses: JS-DevTools/npm-publish@v4
        with:
          package: ./npm-module-build/package.json
          strategy: upgrade
          provenance: true
          token: ${{ secrets.NPM_TOKEN }}
