name: Run Tests
on:
  push:
    branches-ignore:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 24]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install
        run: npm ci

      - name: Run tests
        run: npm run test-ci

      - name: Generating coverage badges
        if: matrix.node-version == 20
        uses: 'jpb06/jest-badges-action@latest'
        with:
          branches: main
